version: "3.9"

services:
  order-generator:
    ports:
      - "5080:80"
    build:
      context: ./src/OrderService.OrderGenerator
      dockerfile: Dockerfile
      
  customer-service:
    ports:
      - "5081:80"
    build:
      context: ./src/OrderService.CustomerService
      dockerfile: Dockerfile
    depends_on:
      - order-generator
    
  customer-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer_db

  adminer:
    image: adminer
    ports:
      - "6432:8080"
  
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT